var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"profile-sidebar"},[_vm._m(0),_vm._v(" "),_vm._m(1),_vm._v(" "),_c('div',{staticClass:"custom-sidebar-nav"},[_c('ul',[_c('li',[_c('router-link',{class:{'active': _vm.currentPath == 'mentee-dashboard'},attrs:{"to":"/mentee/index"}},[_c('i',{staticClass:"fas fa-home"}),_vm._v("Dashboard "),_c('span',[_c('i',{staticClass:"fas fa-chevron-right"})])])],1),_vm._v(" "),_c('li',[_c('router-link',{class:{'active': _vm.currentPath == 'mentee-bookings'},attrs:{"to":"/mentee/bookings"}},[_c('i',{staticClass:"fas fa-clock"}),_vm._v("Bookings "),_c('span',[_c('i',{staticClass:"fas fa-chevron-right"})])])],1),_vm._v(" "),_c('li',[_c('router-link',{class:{'active': _vm.currentPath == 'mentee-chat'},attrs:{"to":"/mentee/chat"}},[_c('i',{staticClass:"fas fa-comments"}),_vm._v("Messages "),_c('span',[_c('i',{staticClass:"fas fa-chevron-right"})])])],1),_vm._v(" "),_c('li',[_c('router-link',{class:{'active': _vm.currentPath == 'mentee-favourites'},attrs:{"to":"/mentee/favourites"}},[_c('i',{staticClass:"fas fa-star"}),_vm._v("Favourites "),_c('span',[_c('i',{staticClass:"fas fa-chevron-right"})])])],1),_vm._v(" "),_c('li',[_c('router-link',{class:{'active': _vm.currentPath == 'mentee-mentor-profile'},attrs:{"to":"/mentee/mentor-profile"}},[_c('i',{staticClass:"fas fa-user-cog"}),_vm._v("Profile "),_c('span',[_c('i',{staticClass:"fas fa-chevron-right"})])])],1),_vm._v(" "),_c('li',[_c('router-link',{attrs:{"to":"/pages/login"}},[_c('i',{staticClass:"fas fa-sign-out-alt"}),_vm._v("Logout "),_c('span',[_c('i',{staticClass:"fas fa-chevron-right"})])])],1)])])])}
var staticRenderFns = [function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"user-widget"},[_c('div',{staticClass:"pro-avatar"},[_vm._v("JD")]),_vm._v(" "),_c('div',{staticClass:"rating"},[_c('i',{staticClass:"fas fa-star filled"}),_vm._v(" "),_c('i',{staticClass:"fas fa-star filled"}),_vm._v(" "),_c('i',{staticClass:"fas fa-star filled"}),_vm._v(" "),_c('i',{staticClass:"fas fa-star filled"}),_vm._v(" "),_c('i',{staticClass:"fas fa-star"})]),_vm._v(" "),_c('div',{staticClass:"user-info-cont"},[_c('h4',{staticClass:"usr-name"},[_vm._v("Jonathan Doe")]),_vm._v(" "),_c('p',{staticClass:"mentor-type"},[_vm._v("English Literature (M.A)")])])])},function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"progress-bar-custom"},[_c('h6',[_vm._v("Complete your profiles >")]),_vm._v(" "),_c('div',{staticClass:"pro-progress"},[_c('div',{staticClass:"tooltip-toggle",attrs:{"tabindex":"0"}}),_vm._v(" "),_c('div',{staticClass:"tooltip"},[_vm._v("80%")])])])}]
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-0e910639","hasScoped":false,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/components/layouts/website/mentee/SideBar.vue
// module id = null
// module chunks = 