var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('footer',{staticClass:"footer"},[_c('div',{staticClass:"footer-top"},[_c('div',{staticClass:"container-fluid"},[_c('div',{staticClass:"row"},[_vm._m(0),_vm._v(" "),_c('div',{staticClass:"col-lg-3 col-md-6"},[_c('div',{staticClass:"footer-widget footer-menu"},[_c('h2',{staticClass:"footer-title"},[_vm._v("For Mentee")]),_vm._v(" "),_c('ul',[_c('li',[_c('router-link',{attrs:{"to":"/mentee/mentor-search"}},[_vm._v("Search Mentors")])],1),_vm._v(" "),_c('li',[_c('router-link',{attrs:{"to":"/pages/login"}},[_vm._v("Login")])],1),_vm._v(" "),_c('li',[_c('router-link',{attrs:{"to":"/pages/register"}},[_vm._v("Register")])],1),_vm._v(" "),_c('li',[_c('router-link',{attrs:{"to":"/booking"}},[_vm._v("Booking")])],1),_vm._v(" "),_c('li',[_c('router-link',{attrs:{"to":"/mentee/index"}},[_vm._v("Mentee Dashboard")])],1)])])]),_vm._v(" "),_c('div',{staticClass:"col-lg-3 col-md-6"},[_c('div',{staticClass:"footer-widget footer-menu"},[_c('h2',{staticClass:"footer-title"},[_vm._v("For Mentors")]),_vm._v(" "),_c('ul',[_c('li',[_c('router-link',{attrs:{"to":"/mentor/appointments"}},[_vm._v("Appointments")])],1),_vm._v(" "),_c('li',[_c('router-link',{attrs:{"to":"/mentor/chat"}},[_vm._v("Chat")])],1),_vm._v(" "),_c('li',[_c('router-link',{attrs:{"to":"/pages/login"}},[_vm._v("Login")])],1),_vm._v(" "),_c('li',[_c('router-link',{attrs:{"to":"/pages/register"}},[_vm._v("Register")])],1),_vm._v(" "),_c('li',[_c('router-link',{attrs:{"to":"/mentor/index"}},[_vm._v("Mentor Dashboard")])],1)])])]),_vm._v(" "),_vm._m(1)])])]),_vm._v(" "),_vm._m(2)])}
var staticRenderFns = [function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"col-lg-3 col-md-6"},[_c('div',{staticClass:"footer-widget footer-about"},[_c('div',{staticClass:"footer-logo"},[_c('img',{attrs:{"src":require("@/assets/img/website/logo.png"),"alt":"logo"}})]),_vm._v(" "),_c('div',{staticClass:"footer-about-content"},[_c('p',[_vm._v("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ")]),_vm._v(" "),_c('div',{staticClass:"social-icon"},[_c('ul',[_c('li',[_c('a',{attrs:{"href":"#","target":"_blank"}},[_c('i',{staticClass:"fab fa-facebook-f"})])]),_vm._v(" "),_c('li',[_c('a',{attrs:{"href":"#","target":"_blank"}},[_c('i',{staticClass:"fab fa-twitter"})])]),_vm._v(" "),_c('li',[_c('a',{attrs:{"href":"#","target":"_blank"}},[_c('i',{staticClass:"fab fa-linkedin-in"})])]),_vm._v(" "),_c('li',[_c('a',{attrs:{"href":"#","target":"_blank"}},[_c('i',{staticClass:"fab fa-instagram"})])]),_vm._v(" "),_c('li',[_c('a',{attrs:{"href":"#","target":"_blank"}},[_c('i',{staticClass:"fab fa-dribbble"})])])])])])])])},function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"col-lg-3 col-md-6"},[_c('div',{staticClass:"footer-widget footer-contact"},[_c('h2',{staticClass:"footer-title"},[_vm._v("Contact Us")]),_vm._v(" "),_c('div',{staticClass:"footer-contact-info"},[_c('div',{staticClass:"footer-address"},[_c('span',[_c('i',{staticClass:"fas fa-map-marker-alt"})]),_vm._v(" "),_c('p',[_vm._v(" 3556  Beech Street, San Francisco,"),_c('br'),_vm._v(" California, CA 94108 ")])]),_vm._v(" "),_c('p',[_c('i',{staticClass:"fas fa-phone-alt"}),_vm._v("\r\n                                    +1 315 369 5943\r\n                                ")]),_vm._v(" "),_c('p',{staticClass:"mb-0"},[_c('i',{staticClass:"fas fa-envelope"}),_vm._v("\r\n                                    mentoring@example.com\r\n                                ")])])])])},function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"footer-bottom"},[_c('div',{staticClass:"container-fluid"},[_c('div',{staticClass:"copyright"},[_c('div',{staticClass:"row"},[_c('div',{staticClass:"col-12 text-center"},[_c('div',{staticClass:"copyright-text"},[_c('p',{staticClass:"mb-0"},[_vm._v("© 2020 Mentoring. All rights reserved.")])])])])])])])}]
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-2293be82","hasScoped":false,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/components/layouts/website/Footer.vue
// module id = null
// module chunks = 