var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"account-page"},[_c('div',{staticClass:"main-wrapper"},[_c('div',{staticClass:"bg-pattern-style"},[_c('div',{staticClass:"content"},[_c('div',{staticClass:"account-content"},[_c('div',{staticClass:"account-box"},[_c('div',{staticClass:"login-right"},[_vm._m(0),_vm._v(" "),_c('form',[_vm._m(1),_vm._v(" "),_vm._m(2),_vm._v(" "),_c('div',{staticClass:"text-right"},[_c('router-link',{staticClass:"forgot-link",attrs:{"to":"/pages/forgot-password"}},[_vm._v("Forgot Password ?")])],1),_vm._v(" "),_c('button',{staticClass:"btn btn-primary login-btn",attrs:{"type":"button"},on:{"click":function($event){return _vm.$router.push('/mentor/index')}}},[_vm._v("Login")]),_vm._v(" "),_c('div',{staticClass:"text-center dont-have"},[_vm._v("Don’t have an account? "),_c('router-link',{attrs:{"to":"/pages/register"}},[_vm._v("Register")])],1)])])])])])])])])}
var staticRenderFns = [function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"login-header"},[_c('h3',[_vm._v("Login "),_c('span',[_vm._v("Mentoring")])]),_vm._v(" "),_c('p',{staticClass:"text-muted"},[_vm._v("Access to our dashboard")])])},function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"form-group"},[_c('label',{staticClass:"form-control-label"},[_vm._v("Email Address")]),_vm._v(" "),_c('input',{staticClass:"form-control",attrs:{"type":"email"}})])},function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"form-group"},[_c('label',{staticClass:"form-control-label"},[_vm._v("Password")]),_vm._v(" "),_c('div',{staticClass:"pass-group"},[_c('input',{staticClass:"form-control pass-input",attrs:{"type":"password"}}),_vm._v(" "),_c('span',{staticClass:"fas fa-eye toggle-password"})])])}]
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-10514b18","hasScoped":false,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/components/website/pages/Login.vue
// module id = null
// module chunks = 