var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"account-page"},[_c('div',{staticClass:"main-wrapper"},[_c('div',{staticClass:"bg-pattern-style bg-pattern-style-register"},[_c('div',{staticClass:"content"},[_c('div',{staticClass:"account-content"},[_c('div',{staticClass:"account-box"},[_c('div',{staticClass:"login-right"},[_vm._m(0),_vm._v(" "),_c('form',[_vm._m(1),_vm._v(" "),_vm._m(2),_vm._v(" "),_vm._m(3),_vm._v(" "),_vm._m(4),_vm._v(" "),_c('button',{staticClass:"btn btn-primary login-btn",attrs:{"type":"button"},on:{"click":function($event){return _vm.$router.push('/')}}},[_vm._v("Create Account")]),_vm._v(" "),_c('div',{staticClass:"account-footer text-center mt-3"},[_vm._v("\n\t\t\t\t\t\t\t\t\t\tAlready have an account? "),_c('router-link',{staticClass:"forgot-link mb-0",attrs:{"to":"/pages/login"}},[_vm._v("Login")])],1)])])])])])])])])}
var staticRenderFns = [function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"login-header"},[_c('h3',[_c('span',[_vm._v("Mentoring")]),_vm._v(" Register")]),_vm._v(" "),_c('p',{staticClass:"text-muted"},[_vm._v("Access to our dashboard")])])},function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"row"},[_c('div',{staticClass:"col-lg-6"},[_c('div',{staticClass:"form-group"},[_c('label',{staticClass:"form-control-label"},[_vm._v("First Name")]),_vm._v(" "),_c('input',{staticClass:"form-control",attrs:{"id":"first-name","type":"text","name":"first_name","autofocus":""}})])]),_vm._v(" "),_c('div',{staticClass:"col-lg-6"},[_c('div',{staticClass:"form-group"},[_c('label',{staticClass:"form-control-label"},[_vm._v("Last Name")]),_vm._v(" "),_c('input',{staticClass:"form-control",attrs:{"id":"last-name","type":"text","name":"last_name"}})])])])},function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"form-group"},[_c('label',{staticClass:"form-control-label"},[_vm._v("Email Address")]),_vm._v(" "),_c('input',{staticClass:"form-control",attrs:{"id":"email","type":"email"}})])},function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"row"},[_c('div',{staticClass:"col-lg-6"},[_c('div',{staticClass:"form-group"},[_c('label',{staticClass:"form-control-label"},[_vm._v("Password")]),_vm._v(" "),_c('input',{staticClass:"form-control",attrs:{"id":"password","type":"password","name":"password"}})])]),_vm._v(" "),_c('div',{staticClass:"col-lg-6"},[_c('div',{staticClass:"form-group"},[_c('label',{staticClass:"form-control-label"},[_vm._v("Confirm Password")]),_vm._v(" "),_c('input',{staticClass:"form-control",attrs:{"id":"password-confirm","type":"password","name":"password_confirmation"}})])])])},function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"form-group"},[_c('div',{staticClass:"custom-control custom-control-xs custom-checkbox"},[_c('input',{staticClass:"custom-control-input",attrs:{"type":"checkbox","name":"agreeCheckboxUser","id":"agree_checkbox_user"}}),_vm._v(" "),_c('label',{staticClass:"custom-control-label",attrs:{"for":"agree_checkbox_user"}},[_vm._v("I agree to Mentoring")]),_vm._v(" "),_c('a',{attrs:{"tabindex":"-1","href":"javascript:void(0);"}},[_vm._v("Privacy Policy")]),_vm._v(" & "),_c('a',{attrs:{"tabindex":"-1","href":"javascript:void(0);"}},[_vm._v(" Terms.")])])])}]
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-1348325c","hasScoped":false,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/components/website/pages/Register.vue
// module id = null
// module chunks = 