var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"main-wrapper"},[_c('layout-header1'),_vm._v(" "),_c('div',{staticClass:"content"},[_c('div',{staticClass:"container-fluid"},[_c('div',{staticClass:"call-wrapper"},[_c('div',{staticClass:"call-main-row"},[_c('div',{staticClass:"call-main-wrapper"},[_c('div',{staticClass:"call-view"},[_c('div',{staticClass:"call-window"},[_c('div',{staticClass:"fixed-header"},[_c('div',{staticClass:"navbar"},[_c('div',{staticClass:"user-details mr-auto"},[_c('div',{staticClass:"float-left user-img"},[_c('router-link',{staticClass:"avatar avatar-sm mr-2",attrs:{"to":"/mentee/mentor-profile","title":"Jonathan Doe"}},[_c('img',{staticClass:"rounded-circle",attrs:{"src":require("@/assets/img/website/user/user.jpg"),"alt":"User Image"}}),_vm._v(" "),_c('span',{staticClass:"status online"})])],1),_vm._v(" "),_c('div',{staticClass:"user-info float-left"},[_c('router-link',{attrs:{"to":"/mentee/mentor-profile"}},[_c('span',[_vm._v("Jonathan Doe")])]),_vm._v(" "),_c('span',{staticClass:"last-seen"},[_vm._v("Online")])],1)]),_vm._v(" "),_vm._m(0)])]),_vm._v(" "),_vm._m(1),_vm._v(" "),_vm._m(2)])])])])])])])],1)}
var staticRenderFns = [function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('ul',{staticClass:"nav float-right custom-menu"},[_c('li',{staticClass:"nav-item dropdown dropdown-action"},[_c('a',{staticClass:"nav-link dropdown-toggle",attrs:{"href":"#","data-toggle":"dropdown","aria-expanded":"false"}},[_c('i',{staticClass:"fa fa-cog"})]),_vm._v(" "),_c('div',{staticClass:"dropdown-menu dropdown-menu-right"},[_c('a',{staticClass:"dropdown-item",attrs:{"href":"javascript:void(0)"}},[_vm._v("Settings")])])])])},function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"call-contents"},[_c('div',{staticClass:"call-content-wrap"},[_c('div',{staticClass:"voice-call-avatar"},[_c('img',{staticClass:"call-avatar",attrs:{"src":require("@/assets/img/website/user/user2.jpg"),"alt":"User Image"}}),_vm._v(" "),_c('span',{staticClass:"username"},[_vm._v("Jonathan Doe")]),_vm._v(" "),_c('span',{staticClass:"call-timing-count"},[_vm._v("00:59")])]),_vm._v(" "),_c('div',{staticClass:"call-users"},[_c('ul',[_c('li',[_c('a',{attrs:{"href":"#"}},[_c('img',{staticClass:"img-fluid",attrs:{"src":require("@/assets/img/website/user/user.jpg"),"alt":"User Image"}}),_vm._v(" "),_c('span',{staticClass:"call-mute"},[_c('i',{staticClass:"fa fa-microphone-slash"})])])])])])])])},function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"call-footer"},[_c('div',{staticClass:"call-icons"},[_c('ul',{staticClass:"call-items"},[_c('li',{staticClass:"call-item"},[_c('a',{attrs:{"href":"#","title":"Enable Video","data-placement":"top","data-toggle":"tooltip"}},[_c('i',{staticClass:"fas fa-video camera"})])]),_vm._v(" "),_c('li',{staticClass:"call-item"},[_c('a',{attrs:{"href":"#","title":"Mute","data-placement":"top","data-toggle":"tooltip"}},[_c('i',{staticClass:"fa fa-microphone microphone"})])]),_vm._v(" "),_c('li',{staticClass:"call-item"},[_c('a',{attrs:{"href":"#","title":"Add User","data-placement":"top","data-toggle":"tooltip"}},[_c('i',{staticClass:"fa fa-user-plus"})])])]),_vm._v(" "),_c('div',{staticClass:"end-call"},[_c('a',{attrs:{"href":"javascript:void(0);"}},[_c('i',{staticClass:"material-icons"},[_vm._v("call_end")])])])])])}]
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-a82266b8","hasScoped":false,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/components/website/pages/Voicecall.vue
// module id = null
// module chunks = 