var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"main-wrapper"},[_c('layout-header'),_vm._v(" "),_c('div',{staticClass:"content"},[_c('div',{staticClass:"container-fluid"},[_c('div',{staticClass:"row"},[_c('div',{staticClass:"col-md-8 offset-md-2"},[_c('div',{staticClass:"account-content"},[_c('div',{staticClass:"row align-items-center justify-content-center"},[_c('div',{staticClass:"col-md-12 col-lg-6 login-right"},[_c('div',{staticClass:"login-header"},[_c('h3',[_vm._v("Mentee Register "),_c('router-link',{attrs:{"to":"/mentor/register"}},[_vm._v("Not a Mentee?")])],1)]),_vm._v(" "),_c('form',[_vm._m(0),_vm._v(" "),_vm._m(1),_vm._v(" "),_vm._m(2),_vm._v(" "),_c('div',{staticClass:"text-right"},[_c('router-link',{staticClass:"forgot-link",attrs:{"to":"/pages/login"}},[_vm._v("Already have an account?")])],1),_vm._v(" "),_c('button',{staticClass:"btn btn-primary btn-block btn-lg login-btn",attrs:{"type":"button"},on:{"click":function($event){return _vm.$router.push('/mentor/index')}}},[_vm._v("Signup")]),_vm._v(" "),_vm._m(3),_vm._v(" "),_vm._m(4)])])])])])])])]),_vm._v(" "),_c('layout-footer')],1)}
var staticRenderFns = [function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"form-group form-focus"},[_c('input',{staticClass:"form-control floating",attrs:{"type":"text"}}),_vm._v(" "),_c('label',{staticClass:"focus-label"},[_vm._v("Name")])])},function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"form-group form-focus"},[_c('input',{staticClass:"form-control floating",attrs:{"type":"text"}}),_vm._v(" "),_c('label',{staticClass:"focus-label"},[_vm._v("Mobile Number")])])},function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"form-group form-focus"},[_c('input',{staticClass:"form-control floating",attrs:{"type":"password"}}),_vm._v(" "),_c('label',{staticClass:"focus-label"},[_vm._v("Create Password")])])},function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"login-or"},[_c('span',{staticClass:"or-line"}),_vm._v(" "),_c('span',{staticClass:"span-or"},[_vm._v("or")])])},function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"row form-row social-login"},[_c('div',{staticClass:"col-6"},[_c('a',{staticClass:"btn btn-facebook btn-block",attrs:{"href":"#"}},[_c('i',{staticClass:"fab fa-facebook-f mr-1"}),_vm._v(" Login")])]),_vm._v(" "),_c('div',{staticClass:"col-6"},[_c('a',{staticClass:"btn btn-google btn-block",attrs:{"href":"#"}},[_c('i',{staticClass:"fab fa-google mr-1"}),_vm._v(" Login")])])])}]
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-f12fb782","hasScoped":false,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/components/website/mentee/Register.vue
// module id = null
// module chunks = 