var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"card post-widget"},[_vm._m(0),_vm._v(" "),_c('div',{staticClass:"card-body"},[_c('ul',{staticClass:"latest-posts"},[_c('li',[_c('div',{staticClass:"post-thumb"},[_c('router-link',{attrs:{"to":"/mentor/blog-details"}},[_c('img',{staticClass:"img-fluid",attrs:{"src":require("@/assets/img/website/blog/blog-thumb-01.jpg"),"alt":""}})])],1),_vm._v(" "),_c('div',{staticClass:"post-info"},[_c('h4',[_c('router-link',{attrs:{"to":"/mentor/blog-details"}},[_vm._v("Lorem Ipsum is simply dummy text of the printing")])],1),_vm._v(" "),_c('p',[_vm._v("4 Dec 2019")])])]),_vm._v(" "),_c('li',[_c('div',{staticClass:"post-thumb"},[_c('router-link',{attrs:{"to":"/mentor/blog-details"}},[_c('img',{staticClass:"img-fluid",attrs:{"src":require("@/assets/img/website/blog/blog-thumb-02.jpg"),"alt":""}})])],1),_vm._v(" "),_c('div',{staticClass:"post-info"},[_c('h4',[_c('router-link',{attrs:{"to":"/mentor/blog-details"}},[_vm._v("It is a long established fact that a reader will be")])],1),_vm._v(" "),_c('p',[_vm._v("3 Dec 2019")])])]),_vm._v(" "),_c('li',[_c('div',{staticClass:"post-thumb"},[_c('router-link',{attrs:{"to":"/mentor/blog-details"}},[_c('img',{staticClass:"img-fluid",attrs:{"src":require("@/assets/img/website/blog/blog-thumb-03.jpg"),"alt":""}})])],1),_vm._v(" "),_c('div',{staticClass:"post-info"},[_c('h4',[_c('router-link',{attrs:{"to":"/mentor/blog-details"}},[_vm._v("here are many variations of passages of Lorem Ipsum")])],1),_vm._v(" "),_c('p',[_vm._v("3 Dec 2019")])])]),_vm._v(" "),_c('li',[_c('div',{staticClass:"post-thumb"},[_c('router-link',{attrs:{"to":"/mentor/blog-details"}},[_c('img',{staticClass:"img-fluid",attrs:{"src":require("@/assets/img/website/blog/blog-thumb-04.jpg"),"alt":""}})])],1),_vm._v(" "),_c('div',{staticClass:"post-info"},[_c('h4',[_c('router-link',{attrs:{"to":"/mentor/blog-details"}},[_vm._v("The standard chunk of Lorem Ipsum used since the")])],1),_vm._v(" "),_c('p',[_vm._v("2 Dec 2019")])])]),_vm._v(" "),_c('li',[_c('div',{staticClass:"post-thumb"},[_c('router-link',{attrs:{"to":"/mentor/blog-details"}},[_c('img',{staticClass:"img-fluid",attrs:{"src":require("@/assets/img/website/blog/blog-thumb-05.jpg"),"alt":""}})])],1),_vm._v(" "),_c('div',{staticClass:"post-info"},[_c('h4',[_c('router-link',{attrs:{"to":"/mentor/blog-details"}},[_vm._v("to generate Lorem Ipsum which looks reasonable.")])],1),_vm._v(" "),_c('p',[_vm._v("1 Dec 2019")])])])])])])}
var staticRenderFns = [function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"card-header"},[_c('h4',{staticClass:"card-title"},[_vm._v("Latest Posts")])])}]
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-467a08e8","hasScoped":false,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/components/website/mentor/LatestPosts.vue
// module id = null
// module chunks = 