var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _vm._m(0)}
var staticRenderFns = [function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"card tags-widget"},[_c('div',{staticClass:"card-header"},[_c('h4',{staticClass:"card-title"},[_vm._v("Tags")])]),_vm._v(" "),_c('div',{staticClass:"card-body"},[_c('ul',{staticClass:"tags"},[_c('li',[_c('a',{staticClass:"tag",attrs:{"href":"#"}},[_vm._v("HTML")])]),_vm._v(" "),_c('li',[_c('a',{staticClass:"tag",attrs:{"href":"#"}},[_vm._v("Css")])]),_vm._v(" "),_c('li',[_c('a',{staticClass:"tag",attrs:{"href":"#"}},[_vm._v("Java Script")])]),_vm._v(" "),_c('li',[_c('a',{staticClass:"tag",attrs:{"href":"#"}},[_vm._v("Jquery")])]),_vm._v(" "),_c('li',[_c('a',{staticClass:"tag",attrs:{"href":"#"}},[_vm._v("Wordpress")])]),_vm._v(" "),_c('li',[_c('a',{staticClass:"tag",attrs:{"href":"#"}},[_vm._v("Php")])]),_vm._v(" "),_c('li',[_c('a',{staticClass:"tag",attrs:{"href":"#"}},[_vm._v("Angular js")])]),_vm._v(" "),_c('li',[_c('a',{staticClass:"tag",attrs:{"href":"#"}},[_vm._v("React js")])]),_vm._v(" "),_c('li',[_c('a',{staticClass:"tag",attrs:{"href":"#"}},[_vm._v("Vue js")])]),_vm._v(" "),_c('li',[_c('a',{staticClass:"tag",attrs:{"href":"#"}},[_vm._v("Photoshop")])]),_vm._v(" "),_c('li',[_c('a',{staticClass:"tag",attrs:{"href":"#"}},[_vm._v("Ajax")])]),_vm._v(" "),_c('li',[_c('a',{staticClass:"tag",attrs:{"href":"#"}},[_vm._v("Json")])]),_vm._v(" "),_c('li',[_c('a',{staticClass:"tag",attrs:{"href":"#"}},[_vm._v("C")])]),_vm._v(" "),_c('li',[_c('a',{staticClass:"tag",attrs:{"href":"#"}},[_vm._v("C++")])]),_vm._v(" "),_c('li',[_c('a',{staticClass:"tag",attrs:{"href":"#"}},[_vm._v("Vb")])]),_vm._v(" "),_c('li',[_c('a',{staticClass:"tag",attrs:{"href":"#"}},[_vm._v("Vb.net")])]),_vm._v(" "),_c('li',[_c('a',{staticClass:"tag",attrs:{"href":"#"}},[_vm._v("Asp.net")])])])])])}]
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-a0a6f808","hasScoped":false,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/components/website/mentor/Tags.vue
// module id = null
// module chunks = 