var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"main-wrapper"},[_c('layout-headeradmin'),_vm._v(" "),_c('layout-sidebar'),_vm._v(" "),_c('div',{staticClass:"page-wrapper"},[_c('div',{staticClass:"content container-fluid"},[_c('div',{staticClass:"page-header"},[_c('div',{staticClass:"row"},[_c('div',{staticClass:"col-sm-12"},[_c('h3',{staticClass:"page-title"},[_vm._v("Add Blog")]),_vm._v(" "),_c('ul',{staticClass:"breadcrumb"},[_c('li',{staticClass:"breadcrumb-item"},[_c('router-link',{attrs:{"to":"/admin/index"}},[_vm._v("Dashboard")])],1),_vm._v(" "),_c('li',{staticClass:"breadcrumb-item active"},[_vm._v("Add Blog")])])])])]),_vm._v(" "),_vm._m(0)])])],1)}
var staticRenderFns = [function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"row"},[_c('div',{staticClass:"col-sm-12"},[_c('div',{staticClass:"card"},[_c('div',{staticClass:"card-body"},[_c('div',{staticClass:"row"},[_c('div',{staticClass:"col-12 blog-details"},[_c('form',[_c('div',{staticClass:"form-group"},[_c('label',[_vm._v("Blog Name")]),_vm._v(" "),_c('input',{staticClass:"form-control",attrs:{"type":"text"}})]),_vm._v(" "),_c('div',{staticClass:"form-group"},[_c('label',[_vm._v("Blog Images")]),_vm._v(" "),_c('div',[_c('input',{staticClass:"form-control",attrs:{"type":"file"}}),_vm._v(" "),_c('small',{staticClass:"form-text text-muted"},[_vm._v("Max. file size: 50 MB. Allowed images: jpg, gif, png. Maximum 10 images only.")])])]),_vm._v(" "),_c('div',{staticClass:"row"},[_c('div',{staticClass:"col-md-6"},[_c('div',{staticClass:"form-group"},[_c('label',[_vm._v("Blog Category")]),_vm._v(" "),_c('select',{staticClass:"select select2-hidden-accessible form-control",attrs:{"tabindex":"-1","aria-hidden":"true"}},[_c('option',[_vm._v("Web Design")]),_vm._v(" "),_c('option',[_vm._v("Web Development")]),_vm._v(" "),_c('option',[_vm._v("App Development")])])])]),_vm._v(" "),_c('div',{staticClass:"col-md-6"},[_c('div',{staticClass:"form-group"},[_c('label',[_vm._v("Blog Sub Category")]),_vm._v(" "),_c('select',{staticClass:"select select2-hidden-accessible form-control",attrs:{"tabindex":"-1","aria-hidden":"true"}},[_c('option',[_vm._v("Html")]),_vm._v(" "),_c('option',[_vm._v("Css")]),_vm._v(" "),_c('option',[_vm._v("Javascript")]),_vm._v(" "),_c('option',[_vm._v("PHP")]),_vm._v(" "),_c('option',[_vm._v("Codeignitor")]),_vm._v(" "),_c('option',[_vm._v("iOS")]),_vm._v(" "),_c('option',[_vm._v("Android")])])])])]),_vm._v(" "),_c('div',{staticClass:"form-group"},[_c('label',[_vm._v("Blog Description")]),_vm._v(" "),_c('textarea',{staticClass:"form-control",attrs:{"cols":"30","rows":"6"}})]),_vm._v(" "),_c('div',{staticClass:"form-group"},[_c('label',{staticClass:"display-block w-100"},[_vm._v("Blog Status")]),_vm._v(" "),_c('div',[_c('div',{staticClass:"custom-control custom-radio custom-control-inline"},[_c('input',{staticClass:"custom-control-input",attrs:{"id":"active","name":"active-blog","value":"active","type":"radio","checked":""}}),_vm._v(" "),_c('label',{staticClass:"custom-control-label",attrs:{"for":"active"}},[_vm._v("Active")])]),_vm._v(" "),_c('div',{staticClass:"custom-control custom-radio custom-control-inline"},[_c('input',{staticClass:"custom-control-input",attrs:{"id":"inactive","name":"active-blog","value":"inactive","type":"radio"}}),_vm._v(" "),_c('label',{staticClass:"custom-control-label",attrs:{"for":"inactive"}},[_vm._v("Inactive")])])])]),_vm._v(" "),_c('div',{staticClass:"m-t-20 text-center"},[_c('button',{staticClass:"btn btn-primary btn-lg"},[_vm._v("Publish Blog")])])])])])])])])])}]
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-97c40ace","hasScoped":false,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/components/admin/addblog.vue
// module id = null
// module chunks = 