var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"main-wrapper"},[_c('layout-headeradmin'),_vm._v(" "),_c('layout-sidebar'),_vm._v(" "),_c('div',{staticClass:"page-wrapper"},[_c('div',{staticClass:"content container-fluid"},[_c('div',{staticClass:"page-header"},[_c('div',{staticClass:"row"},[_c('div',{staticClass:"col"},[_c('h3',{staticClass:"page-title"},[_vm._v("Data Tables")]),_vm._v(" "),_c('ul',{staticClass:"breadcrumb"},[_c('li',{staticClass:"breadcrumb-item"},[_c('router-link',{attrs:{"to":"/admin/index"}},[_vm._v("Dashboard")])],1),_vm._v(" "),_c('li',{staticClass:"breadcrumb-item active"},[_vm._v("Data Tables")])])])])]),_vm._v(" "),_c('div',{staticClass:"row"},[_c('div',{staticClass:"col-sm-12"},[_c('div',{staticClass:"card"},[_vm._m(0),_vm._v(" "),_c('div',{staticClass:"card-body"},[_c('div',{staticClass:"table-responsive"},[_c('table',{staticClass:"datatable table table-stripped"},[_vm._m(1),_vm._v(" "),_c('tbody',_vm._l((_vm.datatables),function(item){return _c('tr',{key:item.id},[_c('td',[_vm._v(_vm._s(item.name))]),_vm._v(" "),_c('td',[_vm._v(_vm._s(item.position))]),_vm._v(" "),_c('td',[_vm._v(_vm._s(item.office))]),_vm._v(" "),_c('td',[_vm._v(_vm._s(item.age))]),_vm._v(" "),_c('td',[_vm._v(_vm._s(item.date))]),_vm._v(" "),_c('td',[_vm._v(_vm._s(item.salary))])])}),0)])])])])])])])])],1)}
var staticRenderFns = [function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"card-header"},[_c('h4',{staticClass:"card-title"},[_vm._v("Default Datatable")]),_vm._v(" "),_c('p',{staticClass:"card-text"},[_vm._v("\n\t\t\t\t\t\t\t\t\t\tThis is the most basic example of the datatables with zero configuration. Use the "),_c('code',[_vm._v(".datatable")]),_vm._v(" class to initialize datatables.\n\t\t\t\t\t\t\t\t\t")])])},function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('thead',[_c('tr',[_c('th',[_vm._v("Name")]),_vm._v(" "),_c('th',[_vm._v("Position")]),_vm._v(" "),_c('th',[_vm._v("Office")]),_vm._v(" "),_c('th',[_vm._v("Age")]),_vm._v(" "),_c('th',[_vm._v("Start date")]),_vm._v(" "),_c('th',[_vm._v("Salary")])])])}]
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-0d910516","hasScoped":false,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/components/admin/datatables.vue
// module id = null
// module chunks = 