var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"main-wrapper"},[_c('layout-headeradmin'),_vm._v(" "),_c('layout-sidebar'),_vm._v(" "),_c('div',{staticClass:"page-wrapper"},[_c('div',{staticClass:"content container-fluid"},[_c('div',{staticClass:"page-header"},[_c('div',{staticClass:"row"},[_c('div',{staticClass:"col-sm-12"},[_c('h3',{staticClass:"page-title"},[_vm._v("Form Mask")]),_vm._v(" "),_c('ul',{staticClass:"breadcrumb"},[_c('li',{staticClass:"breadcrumb-item"},[_c('router-link',{attrs:{"to":"/admin/index"}},[_vm._v("Dashboard")])],1),_vm._v(" "),_c('li',{staticClass:"breadcrumb-item active"},[_vm._v("Form Mask")])])])])]),_vm._v(" "),_vm._m(0)])])],1)}
var staticRenderFns = [function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"row"},[_c('div',{staticClass:"col-sm-12"},[_c('div',{staticClass:"card"},[_c('div',{staticClass:"card-header"},[_c('h5',{staticClass:"card-title"},[_vm._v("Form Mask")]),_vm._v(" "),_c('p',{staticClass:"card-text"},[_vm._v("Input masks can be used to force the user to enter data conform a specific format. Unlike validation, the user can't enter any other key than the ones specified by the mask.")])]),_vm._v(" "),_c('div',{staticClass:"card-body"},[_c('form',{attrs:{"action":"#"}},[_c('div',{staticClass:"form-group"},[_c('label',[_vm._v("Phone")]),_vm._v(" "),_c('input',{staticClass:"form-control",attrs:{"type":"text","id":"phone"}}),_vm._v(" "),_c('span',{staticClass:"form-text text-muted"},[_vm._v("(999) 999-9999")])]),_vm._v(" "),_c('div',{staticClass:"form-group"},[_c('label',[_vm._v("Date")]),_vm._v(" "),_c('input',{staticClass:"form-control",attrs:{"type":"text","id":"date"}}),_vm._v(" "),_c('span',{staticClass:"form-text text-muted"},[_vm._v("dd/mm/yyyy")])]),_vm._v(" "),_c('div',{staticClass:"form-group"},[_c('label',[_vm._v("SSN field 1")]),_vm._v(" "),_c('input',{staticClass:"form-control",attrs:{"type":"text","id":"ssn"}}),_vm._v(" "),_c('span',{staticClass:"form-text text-muted"},[_vm._v("e.g \"999-99-9999\"")])]),_vm._v(" "),_c('div',{staticClass:"form-group"},[_c('label',[_vm._v("Phone field + ext.")]),_vm._v(" "),_c('input',{staticClass:"form-control",attrs:{"type":"text","id":"phoneExt"}}),_vm._v(" "),_c('span',{staticClass:"form-text text-muted"},[_vm._v("+40 999 999 999")])]),_vm._v(" "),_c('div',{staticClass:"form-group"},[_c('label',[_vm._v("Product Key")]),_vm._v(" "),_c('input',{staticClass:"form-control",attrs:{"type":"text","id":"product"}}),_vm._v(" "),_c('span',{staticClass:"form-text text-muted"},[_vm._v("e.g a*-999-a999")])]),_vm._v(" "),_c('div',{staticClass:"form-group"},[_c('label',[_vm._v("Currency")]),_vm._v(" "),_c('input',{staticClass:"form-control",attrs:{"type":"text","id":"currency"}}),_vm._v(" "),_c('span',{staticClass:"form-text text-muted"},[_vm._v("$ 999,999,999.99")])]),_vm._v(" "),_c('div',{staticClass:"form-group"},[_c('label',[_vm._v("Eye Script")]),_vm._v(" "),_c('input',{staticClass:"form-control",attrs:{"type":"text","id":"eyescript"}}),_vm._v(" "),_c('span',{staticClass:"form-text text-muted"},[_vm._v("~9.99 ~9.99 999")])]),_vm._v(" "),_c('div',{staticClass:"form-group"},[_c('label',[_vm._v("Percent")]),_vm._v(" "),_c('input',{staticClass:"form-control",attrs:{"type":"text","id":"pct"}}),_vm._v(" "),_c('span',{staticClass:"form-text text-muted"},[_vm._v("e.g \"99%\"")])]),_vm._v(" "),_c('div',{staticClass:"form-group mb-0"},[_c('label',[_vm._v("Credit Card Number")]),_vm._v(" "),_c('input',{staticClass:"form-control",attrs:{"type":"text","id":"ccn"}}),_vm._v(" "),_c('span',{staticClass:"form-text text-muted"},[_vm._v("e.g \"999.999.999.9999\"")])])])])])])])}]
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-826aa028","hasScoped":false,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/components/admin/formmask.vue
// module id = null
// module chunks = 