var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _vm._m(0)}
var staticRenderFns = [function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('section',{staticClass:"section how-it-works"},[_c('div',{staticClass:"container"},[_c('div',{staticClass:"section-header text-center"},[_c('span',[_vm._v("Mentoring Flow")]),_vm._v(" "),_c('h2',[_vm._v("How does it works ?")]),_vm._v(" "),_c('p',{staticClass:"sub-title"},[_vm._v("Are you looking to join online institutions? Now it's very simple, Sign up with mentoring")])]),_vm._v(" "),_c('div',{staticClass:"row"},[_c('div',{staticClass:"col-12 col-md-6 col-lg-4"},[_c('div',{staticClass:"feature-box text-center"},[_c('div',{staticClass:"feature-header"},[_c('div',{staticClass:"feature-icon"},[_c('span',{staticClass:"circle"}),_vm._v(" "),_c('i',[_c('img',{attrs:{"src":require("@/assets/img/website/icon-1.png"),"alt":""}})])]),_vm._v(" "),_c('div',{staticClass:"feature-cont"},[_c('div',{staticClass:"feature-text"},[_vm._v("Sign up")])])]),_vm._v(" "),_c('p',{staticClass:"mb-0"},[_vm._v("Are you looking to join online Learning? Now it's very simple, Now Sign up")])])]),_vm._v(" "),_c('div',{staticClass:"col-12 col-md-6 col-lg-4"},[_c('div',{staticClass:"feature-box text-center"},[_c('div',{staticClass:"feature-header"},[_c('div',{staticClass:"feature-icon"},[_c('span',{staticClass:"circle"}),_vm._v(" "),_c('i',[_c('img',{attrs:{"src":require("@/assets/img/website/icon-2.png"),"alt":""}})])]),_vm._v(" "),_c('div',{staticClass:"feature-cont"},[_c('div',{staticClass:"feature-text"},[_vm._v("Collaborate")])])]),_vm._v(" "),_c('p',{staticClass:"mb-0"},[_vm._v("Collaborate on your own timing, by scheduling with mentor booking")])])]),_vm._v(" "),_c('div',{staticClass:"col-12 col-md-6 col-lg-4"},[_c('div',{staticClass:"feature-box text-center"},[_c('div',{staticClass:"feature-header"},[_c('div',{staticClass:"feature-icon"},[_c('span',{staticClass:"circle"}),_vm._v(" "),_c('i',[_c('img',{attrs:{"src":require("@/assets/img/website/icon-3.png"),"alt":""}})])]),_vm._v(" "),_c('div',{staticClass:"feature-cont"},[_c('div',{staticClass:"feature-text"},[_vm._v("Improve & Get Back")])])]),_vm._v(" "),_c('p',{staticClass:"mb-0"},[_vm._v("you can gather different skill set, and you can become mentor too")])])])])])])}]
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-54739706","hasScoped":false,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/components/website/MentoringFlow.vue
// module id = null
// module chunks = 