var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('section',{staticClass:"section popular-courses"},[_c('div',{staticClass:"container"},[_vm._m(0),_vm._v(" "),_c('carousel',{attrs:{"items":4,"margin":30,"responsive":{0:{items:1,nav:false},600:{items:4,nav:true}}}},_vm._l((_vm.mentors),function(item){return _c('div',{key:item.id,staticClass:"course-box"},[_c('div',{staticClass:"product"},[_c('div',{staticClass:"product-img"},[_c('router-link',{attrs:{"to":"/mentee/mentor-profile"}},[_c('img',{staticClass:"img-fluid",attrs:{"alt":"","src":_vm.loadImg(item.image),"width":"600","height":"300"}})])],1),_vm._v(" "),_c('div',{staticClass:"product-content"},[_c('h3',{staticClass:"title"},[_c('router-link',{attrs:{"to":"/mentee/mentor-profile"}},[_vm._v(_vm._s(item.name))])],1),_vm._v(" "),_c('div',{staticClass:"author-info"},[_c('div',{staticClass:"author-name"},[_vm._v("\n                                    "+_vm._s(item.specialist)+"\n                                ")])]),_vm._v(" "),_c('div',{staticClass:"rating"},[_c('i',{staticClass:"fas fa-star filled"}),_vm._v(" "),_c('i',{staticClass:"fas fa-star filled"}),_vm._v(" "),_c('i',{staticClass:"fas fa-star filled"}),_vm._v(" "),_c('i',{staticClass:"fas fa-star filled"}),_vm._v(" "),_c('i',{staticClass:"fas fa-star"}),_vm._v(" "),_c('span',{staticClass:"d-inline-block average-rating"},[_vm._v(_vm._s(item.rating))])]),_vm._v(" "),_c('div',{staticClass:"author-country"},[_c('p',{staticClass:"mb-0"},[_c('i',{staticClass:"fas fa-map-marker-alt"}),_vm._v(_vm._s(item.location))])])])])])}),0)],1)])}
var staticRenderFns = [function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"section-header text-center"},[_c('span',[_vm._v("Mentoring Goals")]),_vm._v(" "),_c('h2',[_vm._v("Popular Mentors")]),_vm._v(" "),_c('p',{staticClass:"sub-title"},[_vm._v("Do you want to move on next step? Choose your most popular leaning mentors, it will help you to achieve your professional goals.")])])}]
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-137f3a1c","hasScoped":false,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/components/website/PopularMentors.vue
// module id = null
// module chunks = 